Resources:
    TweetsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sb_tweets_test
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH # Partition key
          - AttributeName: createdAt
            KeyType: RANGE # Sort key
        BillingMode: PAY_PER_REQUEST
        LocalSecondaryIndexes:
          - IndexName: tweetIdCreatedAtIndex
            KeySchema:
              - AttributeName: id
                KeyType: HASH # Partition key
              - AttributeName: createdAt
                KeyType: RANGE # Sort key
            Projection:
              ProjectionType: KEYS_ONLY